const sqlInjection = require('./vulnerabilities/sqlInjection');
const brokenAuth = require('./vulnerabilities/brokenAuth');
const sensitiveDataExposure = require('./vulnerabilities/sensitiveDataExposure');
const xxe = require('./vulnerabilities/xxe');
const brokenAccessControl = require('./vulnerabilities/brokenAccessControl');
const securityMisconfiguration = require('./vulnerabilities/securityMisconfiguration');
const xss = require('./vulnerabilities/xss');
const insecureDeserialization = require('./vulnerabilities/insecureDeserialization');
const knownVulnerableComponent = require('./vulnerabilities/knownVulnerableComponent');
const insufficientLogging = require('./vulnerabilities/insufficientLogging');

console.log('VulnerableApp: OWASP Top 10 Demo (JavaScript)');
console.log('This app contains intentional vulnerabilities for SAST demonstration.');
console.log('SQL Injection Demo:', sqlInjection.getUserById("1 OR 1=1"));
console.log('Broken Auth Demo:', brokenAuth.authenticate('admin', 'wrongpassword'));
console.log('Sensitive Data Exposure Demo:', sensitiveDataExposure.getCreditCardInfo());
console.log('XXE Demo:', xxe.parseXml('<!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/hosts">]><foo>&xxe;</foo>'));
console.log('Broken Access Control Demo:', brokenAccessControl.getAdminResource('user'));
console.log('Security Misconfiguration Demo:', securityMisconfiguration.getDebugInfo());
console.log('XSS Demo:', xss.renderComment("<script>alert('xss')</script>"));
console.log('Insecure Deserialization Demo:', insecureDeserialization.deserializeObject('eyJrZXkiOiJoZWxsbyEifQ=='));
console.log('Known Vulnerable Component Demo:', knownVulnerableComponent.hashPassword('password'));
console.log('Insufficient Logging Demo:', insufficientLogging.login('admin', '1234'));
