name: fortify sast scan
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  security-scan:
    uses: cmhmr/workflows-library/.github/workflows/fortify-sast.yaml@main
    secrets: inherit